services:
  elysia-web-api:
    build:
      context: ./src/bun-elysia
    ports:
      - "3001:3000"
  nuxt-web-api:
    build:
      context: ./src/nitro-nuxt
    ports:
      - "3002:3000"
  express-web-api:
    build:
      context: ./src/node-express
    ports:
      - "3003:3000"
    environment:
      NODE_ENV: production
